language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

matrix:
  # Use PHP 5.4 for coverage reporting.
  include:
    - php: 5.4
      env:
        - secure: "ELSvqXauLq9BoLX52V8TcJX97NFGod6dlwhxC//8vv4f+qDFW2NaNUOajjAn\nsg0Sf5tv9S+RzQnkCIxH96/kZghzvzykQ0+vfyxxc9vtbQc1Yni+xKja+aRW\nW7ZHw24NyiPNxNjHIJYiDaiC89w9qSsoLnZRsU5GjbI3NHqJuGs="

  # PHP 5.5 is still in alpha, so ignore build failures.
  allow_failures:
    - php: 5.5

install: composer install --dev --prefer-source
script:  ./vendor/bin/travis-build
