<?php

/*
 * This file is part of the Typhoon package.
 *
 * Copyright © 2011 Erin Millard
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Type.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'CompositeType.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'BaseCompositeType.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'AndType.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Assertion.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Exception'.DIRECTORY_SEPARATOR.'Exception.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Assertion'.DIRECTORY_SEPARATOR.'Exception'.DIRECTORY_SEPARATOR.'Exception.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Assertion'.DIRECTORY_SEPARATOR.'Exception'.DIRECTORY_SEPARATOR.'MissingArgument.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Assertion'.DIRECTORY_SEPARATOR.'Exception'.DIRECTORY_SEPARATOR.'UnexpectedArgument.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Assertion'.DIRECTORY_SEPARATOR.'Exception'.DIRECTORY_SEPARATOR.'UnexpectedType.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Assertion'.DIRECTORY_SEPARATOR.'ParameterList.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Assertion'.DIRECTORY_SEPARATOR.'Type.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Collection.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'AttributeHolder.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'AttributeSignature.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Attributes.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Attributes'.DIRECTORY_SEPARATOR.'Exception'.DIRECTORY_SEPARATOR.'Exception.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Attributes'.DIRECTORY_SEPARATOR.'Exception'.DIRECTORY_SEPARATOR.'UnsupportedAttribute.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'DynamicType.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'BaseDynamicType.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'TraversableType.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'BaseTraversableType.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Collection'.DIRECTORY_SEPARATOR.'Exception'.DIRECTORY_SEPARATOR.'Exception.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Collection'.DIRECTORY_SEPARATOR.'Exception'.DIRECTORY_SEPARATOR.'UndefinedKey.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Exception'.DIRECTORY_SEPARATOR.'NotImplemented.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'OrType.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Parameter.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'ParameterList.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'ParameterList'.DIRECTORY_SEPARATOR.'Exception'.DIRECTORY_SEPARATOR.'Exception.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'ParameterList'.DIRECTORY_SEPARATOR.'Exception'.DIRECTORY_SEPARATOR.'UndefinedParameter.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Primitive.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Primitive'.DIRECTORY_SEPARATOR.'Boolean.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Primitive'.DIRECTORY_SEPARATOR.'Callback.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Primitive'.DIRECTORY_SEPARATOR.'Integer.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Primitive'.DIRECTORY_SEPARATOR.'Null.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Primitive'.DIRECTORY_SEPARATOR.'String.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Renderer'.DIRECTORY_SEPARATOR.'Type.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Renderer'.DIRECTORY_SEPARATOR.'Type'.DIRECTORY_SEPARATOR.'Typhax.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Type'.DIRECTORY_SEPARATOR.'ArrayType.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Type'.DIRECTORY_SEPARATOR.'Boolean.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Type'.DIRECTORY_SEPARATOR.'Callback.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Type'.DIRECTORY_SEPARATOR.'CallbackWrapper.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Type'.DIRECTORY_SEPARATOR.'Float.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Type'.DIRECTORY_SEPARATOR.'Integer.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Type'.DIRECTORY_SEPARATOR.'Mixed.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Type'.DIRECTORY_SEPARATOR.'Null.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Type'.DIRECTORY_SEPARATOR.'Object.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Type'.DIRECTORY_SEPARATOR.'Resource.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Type'.DIRECTORY_SEPARATOR.'String.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Type'.DIRECTORY_SEPARATOR.'Traversable.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Type'.DIRECTORY_SEPARATOR.'TyphoonType.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'TypeInspector.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'TypeRegistry.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'TypeRegistry'.DIRECTORY_SEPARATOR.'Exception'.DIRECTORY_SEPARATOR.'Exception.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'TypeRegistry'.DIRECTORY_SEPARATOR.'Exception'.DIRECTORY_SEPARATOR.'UnregisteredType.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'TypeRegistry'.DIRECTORY_SEPARATOR.'Exception'.DIRECTORY_SEPARATOR.'UnregisteredTypeAlias.php';
require __DIR__.DIRECTORY_SEPARATOR.'Ezzatron'.DIRECTORY_SEPARATOR.'Typhoon'.DIRECTORY_SEPARATOR.'Typhoon.php';